# ベースイメージを指定
FROM python:3.9-slim

# 作業ディレクトリを設定
WORKDIR /web

# 依存関係ファイルをコピー
COPY requirements_web.txt .
# pipを最新バージョンにアップグレード
RUN pip install --upgrade pip
# 依存関係をインストール
RUN pip install --no-cache-dir -r requirements_web.txt

# ストリームリットの設定を環境変数で指定
ENV STREAMLIT_SERVER_PORT=8501

# コンテナ起動時に実行するコマンドを指定
CMD ["streamlit", "run", "main.py"]
